import Sidebar from "@/components/sidebar";
import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#EEF2F4]">
        <div className="flex flex-col md:flex-row space-y-5 w-full h-screen p-5">
          <Sidebar />
          <main className="flex-1 md:p-6 overflow-y-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
